# Generated by Django 3.1.7 on 2021-03-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SentHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.FileField(upload_to='uploads/')),
                ('Result', models.FloatField(null=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SentHomework', to='panels.homework')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.person')),
                ('homeworks', models.ManyToManyField(related_name='Teacher', to='panels.Homework')),
            ],
            bases=('login.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.person')),
                ('studentCode', models.CharField(max_length=12)),
                ('homeworks', models.ManyToManyField(related_name='Student', to='login.SentHomework')),
            ],
            bases=('login.person',),
        ),
    ]
