# Generated by Django 3.1.7 on 2021-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
        ('login', '0002_auto_20210307_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='homeworks',
            field=models.ManyToManyField(to='panels.Homework'),
        ),
    ]
